channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=23.0.1
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - lz4==4.0.0
  - psutil==5.9.2
  - scikit-learn==1.1.2
  - typing-extensions==4.4.0
name: mlflow-env
