apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
  namespace: default
spec:
  storageClassName: local-storage 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /bitnami/hubdb/data
