apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: default
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /bitnami/jenkins/home
